### ISSUE TITLE
WebRequestService content length issue

### ISSUE THREAD

**Issue by gregarican** [agileharbor/lightspeedAccess#2]
Using this service to push new products into Lightspeed. Randomly I would hit certain products I was iterating through that were hanging up. Debugging the routine uncovered that there was an exception of "Bytes to be written to the stream exceed the Content-Length bytes size specified" being hit in WebRequestService.cs line 56. 

Since the HttpWebRequest class automatically handles the content length, I commented out that line and my routine now runs fine. Shown below. Apparently there are issues parsing the XML contents and programmatically assigning the content length. Depending on the content, and since I'm passing along ItemShop[], Note, Prices[], CustomField[], ItemECommerce, etc. elements I allow HttpWebRequest to inherently do the heavy lifting. The escaped HTML in my ItemECommerce long description strings likely weren't being properly handled for calculated content length.

I tried defining System.Text.UTD8Encoding(false) to affect how the BOM is handled, but only disabling the content length being programmatically defined seemed to fix the issue.

//webRequest.ContentLength = s.Length;

**Comment by gregarican** [comment]
Just checking in regarding this. Not sure if this is an actively-maintained project, but if so I added to my own local copy of it. So products can be added/updated, customers can be added/updated, etc. Would be happy to share my work if there is interest...

**Comment by SShumer** [comment]
You are right, the indication of ContentLength is really redundant.

Thank you for your suggestion to share your work. But this library was developed for a specific range of tasks.  And we do not need to update information about products, customers, etc.
